# Site
repository: samuelceballos04/cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Samuel Ceballos
title: Computer Engineering
email: samuelceballos0204@gmail.com
website: https://samuelceballos04.github.io/CV/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username: SamuelCeballos04
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: Sam Scorsone
# flickr_username: jekyll
instagram_username: samsco04
linkedin_username: samuel-ceballos-murguia-412576253
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: https://media.licdn.com/dms/image/v2/D4E03AQHKLzKOagyflw/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1713480779525?e=1731542400&v=beta&t=H62IRPbIPNvWAci9kKQa7YdGyClFXnRG4h78NIb_hdw
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Samuel and I'm a Computer Engineer. As well as a BI developer, I have experience with web apps and AI projects. Teamwork and commitment are two of my main skills.

  I am most skilled in: <mark>Power BI development</mark> and <mark>Database maintenance</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Digitalization of IGT test
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This project means my first participation on a research article EVER!
        description: | # this will include new lines to allow paragraphs
          I started this project as a way to comply with my social service hours, which are requested in order to get a bachelors degree. This was my first desktop application ever, so we (me and my team) had to learn a lot about installers, packages, dependencies, and development technologies such as Javascript, Python, HTML, and css files.
          This project made us all grow both professionally and as human beings since we were always supporting each other, as a team should be, and getting over everything together. The goal for this project was to bring a psychometric test to digital so we can collect data from several applicants of this test and save it for later analysis. 
          The result was so good, our mentors decided to document this process on a research article and send it to a biomedicine journal.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NXP Semiconductors
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: BI Developer
        caption: March 2024 - Present
        quote: >
          If you can't measure it, you can't control it, if you can't control it, you can't improve it.
        description: | # this will include new lines to allow paragraphs
            There's a lot of implications when you have to follow a process that involves several people to design a microcontroller, or a board. Giving management team several reports to track progress on projects, stoppers and metrics is a part of my job. To make my way through
            all of the data generated by the operations is the part nobody wants to talk about, but for me, that is the other part of my job.

    # content:
    #   - layout: left
    #     title: NXP Semiconductors
    #     # link: boringcompany.com
    #     # link_text: boringcompany.com
    #     sub_title: BI Developer
    #     caption: March 2024 - Present
    #     quote: >
    #       If you can't measure it, you can't control it, if you can't control it, you can't improve it.
    #     description: | # this will include new lines to allow paragraphs
    #         There's a lot of implications when you have to follow a process that involves several people to design a microcontroller, or a board. Giving management team several reports to track progress on projects, stoppers and metrics is a part of my job. To make my way through
    #         all of the data generated by the operations is the part nobody wants to talk about, but for me, that is the other part of my job.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Guadalajara
        caption: 2020 - 2024
        sub_title: BSc Computer Engineer
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          All of the skills I have to this day were learnt first here. I started from scratch, from learning the principles of programming logics to very complex things such as AI.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data science and software engineering some of my other interests and hobbies are:
      - Playing the piano
      - Gaming
      - Music theory
      - Science fiction movies


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
